namespace _2calgo.Model
{
    public static class NotSupportedNames
    {
        public static string[] Mq4 = new[]
            {
                "AccountStopoutLevel",
                "BarsPerWindow",
                "FILE_BIN",
                "FileIsEnding",
                "FileReadArray",
                "FileReadInteger",
                "FileReadNumber",
                "FileSize",
                "FileWriteArray",
                "FileWriteInteger",
                "FileWriteString",
                "FirstVisibleBar",
                "GlobalVariableSetOnCondition",
                "iBWMFI",
                "iGator",
                "iOBV",
                "LONG_VALUE",
                "MessageBox",
                "MODE_EXPIRATION",
                "MODE_MARGINHEDGED",
                "MODE_MARGININIT",
                "MODE_MARGINMAINTENANCE",
                "MODE_STARTING",
                "MODE_SWAPLONG",
                "MODE_SWAPSHORT",
                "OBJ_CHANNEL",
                "OBJ_FIBOFAN",
                "OBJ_GANNLINE",
                "OBJ_PITCHFORK",
                "OBJ_STDDEVCHANNEL",
                "OBJ_TRENDBYANGLE",
                "OBJ_TRIANGLE",
                "OBJPROP_DEVIATION",
                "OBJPROP_SCALE",
                "SEEK_SET",
                "SHORT_VALUE",
                "WindowBarsPerChart",
                "WindowFirstVisibleBar",
                "WindowHandle",
                "WindowIsVisible",
                "WindowOnDropped",
                "WindowPriceMax",
                "WindowPriceMin",
                "WindowScreenShot",
                "WindowsTotal",
                "WindowsTotal",
                "OBJ_GANNFAN",
                "OBJ_GANNGRID",
                "OBJ_FIBOARC",
                "OBJ_FIBOCHANNEL",
                "OBJ_FIBOTIMES",
                "OBJ_EXPANSION",
                "OBJ_ELLIPSE",
                "OBJ_CYCLES",
                "OBJ_REGRESSION",
                "indicator_style1",
                "indicator_style2",
                "indicator_style3",
                "indicator_style4",
                "indicator_style5",
                "indicator_style6",
                "indicator_style7",
                "clrDarkOrange",
                "FileOpen", 
                "FILE_BIN",
                "FILE_READ",
                "FILE_WRITE",
                "FileWriteInteger",
                "SHORT_VALUE",
                "FileClose",
                "FileReadInteger", 
                "FileSeek",
                "SEEK_END",
                "FileFlush",
                "FileWrite",
                "FileWriteString",
                "FileSize",
                "FileDelete",
                "SEEK_CUR",
                "FileReadArray",
                "FileWriteArray",
                "FileReadString",
                "FileIsEnding"
            };

        public static string[] CSharp = new[]
            {
                "using System;"
            };

        public static string[] Mq5Methods = new[]
            {
                "OnCalculate", "OnInit", "OnDeinit", "OnTick", "OnTimer", "OnTester", "OnChartEvent",
            };

        public static string[] Mq5 = new[]
            {
                "__DATE__", "__DATETIME__", "__FILE__", "__FUNCSIG__", "__FUNCTION__", "__LINE__", "__MQL4BUILD__",
                "__MQLBUILD__", "__PATH__", "_LastError", "_RandomSeed", "_StopFlag", "_UninitReason", "ACCOUNT_BALANCE"
                , "ACCOUNT_COMPANY", "ACCOUNT_CREDIT", "ACCOUNT_CURRENCY", "ACCOUNT_EQUITY", "ACCOUNT_FREEMARGIN",
                "ACCOUNT_LEVERAGE", "ACCOUNT_LIMIT_ORDERS", "ACCOUNT_LOGIN", "ACCOUNT_MARGIN", "ACCOUNT_MARGIN_LEVEL",
                "ACCOUNT_MARGIN_SO_CALL", "ACCOUNT_MARGIN_SO_MODE", "ACCOUNT_MARGIN_SO_SO", "ACCOUNT_NAME",
                "ACCOUNT_PROFIT", "ACCOUNT_SERVER", "ACCOUNT_STOPOUT_MODE_MONEY", "ACCOUNT_STOPOUT_MODE_PERCENT",
                "ACCOUNT_TRADE_ALLOWED", "ACCOUNT_TRADE_EXPERT", "ACCOUNT_TRADE_MODE", "ACCOUNT_TRADE_MODE_CONTEST",
                "ACCOUNT_TRADE_MODE_DEMO", "ACCOUNT_TRADE_MODE_REAL", "AccountInfoDouble", "AccountInfoInteger",
                "AccountInfoString", "ANCHOR_CENTER", "ANCHOR_LEFT", "ANCHOR_LEFT_LOWER", "ANCHOR_LEFT_UPPER",
                "ANCHOR_LOWER", "ANCHOR_RIGHT", "ANCHOR_RIGHT_LOWER", "ANCHOR_RIGHT_UPPER", "ANCHOR_UPPER",
                "ArrayCompare", "ArrayFill", "ArrayFree", "ArrayGetAsSeries", "ArrayIsDynamic", "ArrayIsSeries",
                "BORDER_FLAT", "BORDER_RAISED", "BORDER_SUNKEN", "CHAR_MAX", "CHAR_MIN", "CharArrayToString",
                "CHART_AUTOSCROLL", "CHART_BARS", "CHART_BEGIN", "CHART_BRING_TO_TOP", "CHART_CANDLES",
                "CHART_COLOR_ASK", "CHART_COLOR_BACKGROUND", "CHART_COLOR_BID", "CHART_COLOR_CANDLE_BEAR",
                "CHART_COLOR_CANDLE_BULL", "CHART_COLOR_CHART_DOWN", "CHART_COLOR_CHART_LINE", "CHART_COLOR_CHART_UP",
                "CHART_COLOR_FOREGROUND", "CHART_COLOR_GRID", "CHART_COLOR_LAST", "CHART_COLOR_STOP_LEVEL",
                "CHART_COLOR_VOLUME", "CHART_COMMENT", "CHART_CURRENT_POS", "CHART_DRAG_TRADE_LEVELS", "CHART_END",
                "CHART_EVENT_MOUSE_MOVE", "CHART_EVENT_OBJECT_CREATE", "CHART_EVENT_OBJECT_DELETE",
                "CHART_FIRST_VISIBLE_BAR", "CHART_FIXED_MAX", "CHART_FIXED_MIN", "CHART_FIXED_POSITION",
                "CHART_FOREGROUND", "CHART_HEIGHT_IN_PIXELS", "CHART_IS_OBJECT", "CHART_LINE", "CHART_MODE",
                "CHART_MOUSE_SCROLL", "CHART_POINTS_PER_BAR", "CHART_PRICE_MAX", "CHART_PRICE_MIN", "CHART_SCALE",
                "CHART_SCALE_PT_PER_BAR", "CHART_SCALEFIX", "CHART_SCALEFIX_11", "CHART_SHIFT", "CHART_SHIFT_SIZE",
                "CHART_SHOW_ASK_LINE", "CHART_SHOW_BID_LINE", "CHART_SHOW_DATE_SCALE", "CHART_SHOW_GRID",
                "CHART_SHOW_LAST_LINE", "CHART_SHOW_OBJECT_DESCR", "CHART_SHOW_OHLC", "CHART_SHOW_PERIOD_SEP",
                "CHART_SHOW_PRICE_SCALE", "CHART_SHOW_TRADE_LEVELS", "CHART_SHOW_VOLUMES", "CHART_VISIBLE_BARS",
                "CHART_VOLUME_HIDE", "CHART_VOLUME_REAL", "CHART_VOLUME_TICK", "CHART_WIDTH_IN_BARS",
                "CHART_WIDTH_IN_PIXELS", "CHART_WINDOW_HANDLE", "CHART_WINDOW_IS_VISIBLE", "CHART_WINDOW_YDISTANCE",
                "CHART_WINDOWS_TOTAL", "ChartApplyTemplate", "ChartClose", "CHARTEVENT_CHART_CHANGE", "CHARTEVENT_CLICK"
                , "CHARTEVENT_CUSTOM", "CHARTEVENT_CUSTOM_LAST", "CHARTEVENT_KEYDOWN", "CHARTEVENT_MOUSE_MOVE",
                "CHARTEVENT_OBJECT_CHANGE", "CHARTEVENT_OBJECT_CLICK", "CHARTEVENT_OBJECT_CREATE",
                "CHARTEVENT_OBJECT_DELETE", "CHARTEVENT_OBJECT_DRAG", "CHARTEVENT_OBJECT_ENDEDIT", "ChartFirst",
                "ChartGetDouble", "ChartGetInteger", "ChartGetString", "ChartID", "ChartIndicatorDelete",
                "ChartIndicatorName", "ChartIndicatorsTotal", "ChartNavigate", "ChartNext", "ChartOpen", "CharToString",
                "ChartPriceOnDropped", "ChartRedraw", "CHARTS_MAX", "ChartSaveTemplate", "ChartScreenShot",
                "ChartSetDouble", "ChartSetInteger", "ChartSetString", "ChartSetSymbolPeriod", "ChartSymbol",
                "ChartTimeOnDropped", "ChartTimePriceToXY", "ChartWindowFind", "ChartWindowOnDropped", "ChartXOnDropped"
                , "ChartXYToTimePrice", "ChartYOnDropped", "ClientTerminalName", "clrNONE", "ColorToARGB",
                "ColorToString", "CompanyName", "CopyClose", "CopyHigh", "CopyLow", "CopyOpen", "CopyRates",
                "CopyRealVolume", "CopySpread", "CopyTickVolume", "CopyTime", "CORNER_LEFT_LOWER", "CORNER_LEFT_UPPER",
                "CORNER_RIGHT_LOWER", "CORNER_RIGHT_UPPER", "CP_ACP", "CP_MACCP", "CP_OEMCP", "CP_SYMBOL",
                "CP_THREAD_ACP", "CP_UTF7", "CP_UTF8", "DBL_DIG", "DBL_EPSILON", "DBL_MANT_DIG", "DBL_MAX",
                "DBL_MAX_10_EXP", "DBL_MAX_EXP", "DBL_MIN", "DBL_MIN_10_EXP", "DBL_MIN_EXP", "DoubleToString",
                "EnumToString", "ERR_ARRAY_AS_PARAMETER_EXPECTED", "ERR_ARRAY_INDEX_OUT_OF_RANGE", "ERR_ARRAY_INVALID",
                "ERR_CANNOT_CALL_FUNCTION", "ERR_CANNOT_LOAD_LIBRARY", "ERR_CHART_NOREPLY", "ERR_CHART_NOT_FOUND",
                "ERR_CHART_PROP_INVALID", "ERR_CHARTINDICATOR_NOT_FOUND", "ERR_CHARTWINDOW_NOT_FOUND",
                "ERR_CUSTOM_INDICATOR_ERROR", "ERR_DLL_CALLS_NOT_ALLOWED", "ERR_DLLFUNC_CRITICALERROR",
                "ERR_DOUBLE_PARAMETER_EXPECTED", "ERR_END_OF_FILE", "ERR_EXTERNAL_CALLS_NOT_ALLOWED",
                "ERR_FILE_ARRAYRESIZE_ERROR", "ERR_FILE_BIN_STRINGSIZE", "ERR_FILE_BUFFER_ALLOCATION_ERROR",
                "ERR_FILE_CANNOT_CLEAN_DIRECTORY", "ERR_FILE_CANNOT_DELETE", "ERR_FILE_CANNOT_DELETE_DIRECTORY",
                "ERR_FILE_CANNOT_OPEN", "ERR_FILE_CANNOT_REWRITE", "ERR_FILE_DIRECTORY_NOT_EXIST",
                "ERR_FILE_INCOMPATIBLE", "ERR_FILE_INVALID_HANDLE", "ERR_FILE_IS_DIRECTORY", "ERR_FILE_NOT_BIN",
                "ERR_FILE_NOT_CSV", "ERR_FILE_NOT_DIRECTORY", "ERR_FILE_NOT_EXIST", "ERR_FILE_NOT_TOREAD",
                "ERR_FILE_NOT_TOWRITE", "ERR_FILE_NOT_TXT", "ERR_FILE_NOT_TXTORCSV", "ERR_FILE_READ_ERROR",
                "ERR_FILE_STRINGRESIZE_ERROR", "ERR_FILE_STRUCT_WITH_OBJECTS", "ERR_FILE_TOO_LONG_FILENAME",
                "ERR_FILE_TOO_MANY_OPENED", "ERR_FILE_WRITE_ERROR", "ERR_FILE_WRONG_DIRECTORYNAME",
                "ERR_FILE_WRONG_FILENAME", "ERR_FILE_WRONG_HANDLE", "ERR_FORMAT_TOO_MANY_FORMATTERS",
                "ERR_FORMAT_TOO_MANY_PARAMETERS", "ERR_FUNC_NOT_ALLOWED_IN_TESTING", "ERR_FUNCTION_NOT_CONFIRMED",
                "ERR_GLOBAL_VARIABLE_NOT_FOUND", "ERR_GLOBAL_VARIABLES_PROCESSING", "ERR_INCOMPATIBLE_ARRAYS",
                "ERR_INCOMPATIBLE_FILEACCESS", "ERR_INCORRECT_SERIESARRAY_USING", "ERR_INDICATOR_CANNOT_INIT",
                "ERR_INDICATOR_CANNOT_LOAD", "ERR_INTEGER_PARAMETER_EXPECTED", "ERR_INTERNAL_ERROR",
                "ERR_INVALID_FUNCTION_PARAMSCNT", "ERR_INVALID_FUNCTION_PARAMVALUE", "ERR_INVALID_POINTER",
                "ERR_INVALID_PRICE_PARAM", "ERR_LONGS_NOT_ALLOWED", "ERR_MALFUNCTIONAL_TRADE",
                "ERR_NO_MEMORY_FOR_ARRAYSTRING", "ERR_NO_MEMORY_FOR_CALL_STACK", "ERR_NO_MEMORY_FOR_PARAM_STRING",
                "ERR_NO_MEMORY_FOR_RETURNED_STR", "ERR_NO_MEMORY_FOR_TEMP_STRING", "ERR_NO_OBJECT_NAME",
                "ERR_NO_ORDER_SELECTED", "ERR_NO_SPECIFIED_SUBWINDOW", "ERR_NOT_ENOUGH_RIGHTS",
                "ERR_NOT_ENOUGH_STACK_FOR_PARAM", "ERR_NOT_INITIALIZED_ARRAY", "ERR_NOT_INITIALIZED_ARRAYSTRING",
                "ERR_NOT_INITIALIZED_STRING", "ERR_NOTIFICATION_ERROR", "ERR_NOTIFICATION_PARAMETER",
                "ERR_NOTIFICATION_SETTINGS", "ERR_NOTIFICATION_TOO_FREQUENT", "ERR_OBJECT_ALREADY_EXISTS",
                "ERR_OBJECT_COORDINATES_ERROR", "ERR_OBJECT_DOES_NOT_EXIST", "ERR_OUT_OF_MEMORY",
                "ERR_RECURSIVE_STACK_OVERFLOW", "ERR_REMAINDER_FROM_ZERO_DIVIDE", "ERR_RESOURCE_DUPLICATED",
                "ERR_RESOURCE_NOT_FOUND", "ERR_RESOURCE_NOT_SUPPORTED", "ERR_SEND_MAIL_ERROR", "ERR_SHORTS_NOT_ALLOWED",
                "ERR_SOME_ARRAY_ERROR", "ERR_SOME_FILE_ERROR", "ERR_SOME_OBJECT_ERROR", "ERR_STRING_FUNCTION_INTERNAL",
                "ERR_STRING_PARAMETER_EXPECTED", "ERR_SYMBOL_SELECT", "ERR_SYSTEM_BUSY", "ERR_TOO_LONG_STRING",
                "ERR_TOO_MANY_OPENED_FILES", "ERR_TRADE_ERROR", "ERR_TRADE_NOT_ALLOWED", "ERR_UNKNOWN_COMMAND",
                "ERR_UNKNOWN_OBJECT_PROPERTY", "ERR_UNKNOWN_OBJECT_TYPE", "ERR_UNKNOWN_SYMBOL", "ERR_USER_ERROR_FIRST",
                "ERR_WRONG_FILE_NAME", "ERR_WRONG_FUNCTION_POINTER", "ERR_WRONG_JUMP", "ERR_ZERO_DIVIDE",
                "EventChartCustom", "EventKillTimer", "EventSetMillisecondTimer", "EventSetTimer", "FILE_ACCESS_DATE",
                "FILE_ANSI", "FILE_COMMON", "FILE_CREATE_DATE", "FILE_END", "FILE_EXISTS", "FILE_IS_ANSI",
                "FILE_IS_BINARY", "FILE_IS_COMMON", "FILE_IS_CSV", "FILE_IS_READABLE", "FILE_IS_TEXT",
                "FILE_IS_WRITABLE", "FILE_LINE_END", "FILE_MODIFY_DATE", "FILE_POSITION", "FILE_REWRITE",
                "FILE_SHARE_READ", "FILE_SHARE_WRITE", "FILE_SIZE", "FILE_TXT", "FILE_UNICODE", "FileCopy",
                "FileFindClose", "FileFindFirst", "FileFindNext", "FileGetInteger", "FileIsExist", "FileMove",
                "FileReadBool", "FileReadDatetime", "FileReadFloat", "FileReadLong", "FileReadStruct", "FileWriteFloat",
                "FileWriteLong", "FileWriteStruct", "FLT_DIG", "FLT_EPSILON", "FLT_MANT_DIG", "FLT_MAX",
                "FLT_MAX_10_EXP", "FLT_MAX_EXP", "FLT_MIN", "FLT_MIN_10_EXP", "FLT_MIN_EXP", "FolderClean",
                "FolderCreate", "FolderDelete", "GANN_DOWN_TREND", "GANN_UP_TREND", "GlobalVariablesFlush",
                "GlobalVariableTemp", "GlobalVariableTime", "IDABORT", "IDCONTINUE", "IDIGNORE", "IDRETRY", "IDTRYAGAIN"
                , "iEnvelopesOnArray", "INDICATOR_CALCULATIONS", "INDICATOR_COLOR_INDEX", "INDICATOR_DATA",
                "INDICATOR_DIGITS", "INDICATOR_HEIGHT", "INDICATOR_LEVELCOLOR", "INDICATOR_LEVELS",
                "INDICATOR_LEVELSTYLE", "INDICATOR_LEVELTEXT", "INDICATOR_LEVELVALUE", "INDICATOR_LEVELWIDTH",
                "INDICATOR_MAXIMUM", "INDICATOR_MINIMUM", "INDICATOR_SHORTNAME", "IndicatorSetDouble",
                "IndicatorSetInteger", "IndicatorSetString", "INT_MAX", "INT_MIN", "IntegerToString", "INVALID_HANDLE",
                "IS_DEBUG_MODE", "IS_PROFILE_MODE", "LICENSE_DEMO", "LICENSE_FREE", "LICENSE_FULL", "LICENSE_TIME",
                "LONG_MAX", "LONG_MIN", "M_1_PI", "M_2_PI", "M_2_SQRTPI", "M_E", "M_LN10", "M_LN2", "M_LOG10E",
                "M_LOG2E", "M_PI", "M_PI_2", "M_PI_4", "M_SQRT1_2", "M_SQRT2", "MathArcsin", "MathIsValidNumber",
                "MB_ABORTRETRYIGNORE", "MB_CANCELTRYCONTINUE", "MB_DEFBUTTON1", "MB_DEFBUTTON2", "MB_DEFBUTTON3",
                "MB_DEFBUTTON4", "MB_ICONERROR", "MB_ICONEXCLAMATION", "MB_ICONHAND", "MB_OKCANCEL", "MB_RETRYCANCEL",
                "MB_YESNOCANCEL", "MODE_VOLUME", "MQL_DEBUG", "MQL_DLLS_ALLOWED", "MQL_FRAME_MODE", "MQL_LICENSE_TYPE",
                "MQL_OPTIMIZATION", "MQL_PROFILER", "MQL_PROGRAM_NAME", "MQL_PROGRAM_PATH", "MQL_PROGRAM_TYPE",
                "MQL_SIGNALS_ALLOWED", "MQL_TESTER", "MQL_TRADE_ALLOWED", "MQL_VISUAL_MODE", "MqlDateTime",
                "MQLInfoInteger", "MQLInfoString", "MqlRates", "MqlTick", "OBJ_ALL_PERIODS", "OBJ_ARROW_BUY",
                "OBJ_ARROW_CHECK", "OBJ_ARROW_DOWN", "OBJ_ARROW_LEFT_PRICE", "OBJ_ARROW_RIGHT_PRICE", "OBJ_ARROW_SELL",
                "OBJ_ARROW_STOP", "OBJ_ARROW_THUMB_DOWN", "OBJ_ARROW_THUMB_UP", "OBJ_ARROW_UP", "OBJ_BITMAP",
                "OBJ_BITMAP_LABEL", "OBJ_BUTTON", "OBJ_EDIT", "OBJ_EVENT", "OBJ_NO_PERIODS",
                "OBJ_PERIOD_D1", "OBJ_PERIOD_H4", "OBJ_PERIOD_MN1", "OBJ_PERIOD_W1", "OBJ_RECTANGLE_LABEL",
                "OBJPROP_ALIGN", "OBJPROP_ANCHOR", "OBJPROP_BGCOLOR", "OBJPROP_BMPFILE",
                "OBJPROP_BORDER_COLOR", "OBJPROP_BORDER_TYPE", "OBJPROP_CHART_ID", "OBJPROP_CHART_SCALE",
                "OBJPROP_CREATETIME", "OBJPROP_DATE_SCALE", "OBJPROP_DRAWLINES", "OBJPROP_ELLIPSE", "OBJPROP_FILL",
                "OBJPROP_FONT", "OBJPROP_HIDDEN", "OBJPROP_LEVELS", "OBJPROP_LEVELTEXT", "OBJPROP_LEVELVALUE",
                "OBJPROP_NAME", "OBJPROP_PERIOD", "OBJPROP_PRICE", "OBJPROP_PRICE_SCALE", "OBJPROP_RAY_RIGHT",
                "OBJPROP_READONLY", "OBJPROP_SELECTABLE", "OBJPROP_SELECTED", "OBJPROP_STATE", "OBJPROP_SYMBOL",
                "OBJPROP_TEXT", "OBJPROP_TIME", "OBJPROP_TOOLTIP", "OBJPROP_TYPE", "OBJPROP_XOFFSET", "OBJPROP_XSIZE",
                "OBJPROP_YOFFSET", "OBJPROP_YSIZE", "OBJPROP_ZORDER", "PERIOD_CURRENT", "PERIOD_H12", "PERIOD_H2",
                "PERIOD_H3", "PERIOD_H6", "PERIOD_H8", "PERIOD_M10", "PERIOD_M12", "PERIOD_M2", "PERIOD_M20",
                "PERIOD_M3", "PERIOD_M4", "PERIOD_M6", "POINTER_AUTOMATIC", "POINTER_DYNAMIC", "POINTER_INVALID",
                "PriceOnDropped", "PROGRAM_EXPERT", "PROGRAM_INDICATOR", "PROGRAM_SCRIPT", "REASON_CLOSE",
                "REASON_INITFAILED", "REASON_PROGRAM", "REASON_TEMPLATE", "SHORT_MAX", "SHORT_MIN", "ShortArrayToString"
                , "ShortToString", "SIGNAL_BASE_AUTHOR_LOGIN", "SIGNAL_BASE_BALANCE", "SIGNAL_BASE_BROKER",
                "SIGNAL_BASE_BROKER_SERVER", "SIGNAL_BASE_DATE_PUBLISHED", "SIGNAL_BASE_DATE_STARTED",
                "SIGNAL_BASE_EQUITY", "SIGNAL_BASE_GAIN", "SIGNAL_BASE_ID", "SIGNAL_BASE_LEVERAGE",
                "SIGNAL_BASE_MAX_DRAWDOWN", "SIGNAL_BASE_NAME", "SIGNAL_BASE_PIPS", "SIGNAL_BASE_PRICE",
                "SIGNAL_BASE_RATING", "SIGNAL_BASE_ROI", "SIGNAL_BASE_SUBSCRIBERS", "SIGNAL_BASE_TRADE_MODE",
                "SIGNAL_BASE_TRADES", "SIGNAL_INFO_CONFIRMATIONS_DISABLED", "SIGNAL_INFO_COPY_SLTP",
                "SIGNAL_INFO_DEPOSIT_PERCENT", "SIGNAL_INFO_ID", "SIGNAL_INFO_NAME", "SIGNAL_INFO_SUBSCRIBTION_ENABLED",
                "SIGNAL_INFO_TERMS_AGREE", "SignalBaseGetDouble", "SignalBaseGetInteger", "SignalBaseGetString",
                "SignalBaseSelect", "SignalBaseTotal", "SignalInfoGetDouble", "SignalInfoGetInteger",
                "SignalInfoGetString", "SignalInfoSetDouble", "SignalInfoSetInteger", "SignalSubscribe",
                "SignalUnsubscribe", "STAT_BALANCE_DD", "STAT_BALANCE_DD_RELATIVE", "STAT_BALANCE_DDREL_PERCENT",
                "STAT_BALANCEDD_PERCENT", "STAT_BALANCEMIN", "STAT_CONLOSSMAX", "STAT_CONLOSSMAX_TRADES",
                "STAT_CONPROFITMAX", "STAT_CONPROFITMAX_TRADES", "STAT_CUSTOM_ONTESTER", "STAT_DEALS", "STAT_EQUITY_DD",
                "STAT_EQUITY_DD_RELATIVE", "STAT_EQUITY_DDREL_PERCENT", "STAT_EQUITYDD_PERCENT", "STAT_EQUITYMIN",
                "STAT_EXPECTED_PAYOFF", "STAT_GROSS_LOSS", "STAT_GROSS_PROFIT", "STAT_INITIAL_DEPOSIT",
                "STAT_LONG_TRADES", "STAT_LOSS_TRADES", "STAT_LOSSTRADES_AVGCON", "STAT_MAX_CONLOSS_TRADES",
                "STAT_MAX_CONLOSSES", "STAT_MAX_CONPROFIT_TRADES", "STAT_MAX_CONWINS", "STAT_MAX_LOSSTRADE",
                "STAT_MAX_PROFITTRADE", "STAT_MIN_MARGINLEVEL", "STAT_PROFIT", "STAT_PROFIT_FACTOR",
                "STAT_PROFIT_LONGTRADES", "STAT_PROFIT_SHORTTRADES", "STAT_PROFIT_TRADES", "STAT_PROFITTRADES_AVGCON",
                "STAT_RECOVERY_FACTOR", "STAT_SHARPE_RATIO", "STAT_SHORT_TRADES", "STAT_TRADES", "STAT_WITHDRAWAL",
                "STO_CLOSECLOSE", "STO_LOWHIGH", "StringAdd", "StringBufferLen", "StringCompare", "StringFill",
                "StringFormat", "StringGetCharacter", "StringInit", "StringSetCharacter", "StringToCharArray",
                "StringToColor", "StringToInteger", "StringToLower", "StringToShortArray", "StringToTime",
                "StringToUpper", "StructToTime", "SYMBOL_CHECKSIGN", "SYMBOL_STOPSIGN", "SYMBOL_THUMBSDOWN",
                "SYMBOL_THUMBSUP", "SymbolInfoDouble", "SymbolInfoInteger", "SymbolInfoSessionQuote",
                "SymbolInfoSessionTrade", "SymbolInfoString", "SymbolInfoTick", "SymbolSelect", "SymbolsTotal",
                "TERMINAL_BUILD", "TERMINAL_CODEPAGE", "TERMINAL_COMMONDATA_PATH", "TERMINAL_COMMUNITY_ACCOUNT",
                "TERMINAL_COMMUNITY_BALANCE", "TERMINAL_COMMUNITY_CONNECTION", "TERMINAL_COMPANY", "TERMINAL_CONNECTED",
                "TERMINAL_CPU_CORES", "TERMINAL_DATA_PATH", "TERMINAL_DISK_SPACE", "TERMINAL_DLLS_ALLOWED",
                "TERMINAL_EMAIL_ENABLED", "TERMINAL_FTP_ENABLED", "TERMINAL_LANGUAGE", "TERMINAL_MAXBARS",
                "TERMINAL_MEMORY_AVAILABLE", "TERMINAL_MEMORY_PHYSICAL", "TERMINAL_MEMORY_TOTAL", "TERMINAL_MEMORY_USED"
                , "TERMINAL_MQID", "TERMINAL_NAME", "TERMINAL_NOTIFICATIONS_ENABLED", "TERMINAL_PATH",
                "TERMINAL_TRADE_ALLOWED", "TerminalInfoDouble", "TerminalName", "TimeDaylightSavings", "TimeGMTOffset",
                "TimeOnDropped", "TimeToStruct", "UCHAR_MAX", "UINT_MAX", "ULONG_MAX", "USHORT_MAX", "VOLUME_REAL",
                "VOLUME_TICK", "WindowPriceOnDropped", "WindowTimeOnDropped", "WindowXOnDropped", "WindowYOnDropped",
                "WRONG_VALUE"
            };
    }
}