const string xArrow = "✖";

public static string GetArrowByCode(int code)
{
    switch (code) 
	{
		case 0:
			return string.Empty;
        case 32:
            return " ";
        case 33:
            return "✏";
        case 34:
            return "✂";
        case 35:
            return "✁";
        case 40:
            return "☎";
        case 41:
            return "✆";
        case 42:
            return "✉";
        case 54:
            return "⌛";
        case 55:
            return "⌨";
        case 62:
            return "✇";
        case 63:
            return "✍";
        case 65:
            return "✌";
        case 69:
            return "☜";
        case 70:
            return "☞";
        case 71:
            return "☝";
        case 72:
            return "☟";
        case 74:
            return "☺";
        case 76:
            return "☹";
        case 78:
            return "☠";
        case 79:
            return "⚐";
        case 81:
            return "✈";
        case 82:
            return "☼";
        case 84:
            return "❄";
        case 86:
            return "✞";
        case 88:
            return "✠";
        case 89:
            return "✡";
        case 90:
            return "☪";
        case 91:
            return "☯";
        case 92:
            return "ॐ";
        case 93:
            return "☸";
        case 94:
            return "♈";
        case 95:
            return "♉";
        case 96:
            return "♊";
        case 97:
            return "♋";
        case 98:
            return "♌";
        case 99:
            return "♍";
        case 100:
            return "♎";
        case 101:
            return "♏";
        case 102:
            return "♐";
        case 103:
            return "♑";
        case 104:
            return "♒";
        case 105:
            return "♓";
        case 106:
            return "&";
        case 107:
            return "&";
        case 108:
            return "●";
        case 109:
            return "❍";
        case 110:
            return "■";
        case 111:
        case 112:
            return "□";
        case 113:
            return "❑";
        case 114:
            return "❒";
        case 115:
        case 116:
            return "⧫";
        case 117:
        case 119:
            return "◆";
        case 118:
            return "❖";
        case 120:
            return "⌧";
        case 121:
            return "⍓";
        case 122:
            return "⌘";
        case 123:
            return "❀";
        case 124:
            return "✿";
        case 125:
            return "❝";
        case 126:
            return "❞";
        case 127:
            return "▯";
        case 128:
            return "⓪";
        case 129:
            return "①";
        case 130:
            return "②";
        case 131:
            return "③";
        case 132:
            return "④";
        case 133:
            return "⑤";
        case 134:
            return "⑥";
        case 135:
            return "⑦";
        case 136:
            return "⑧";
        case 137:
            return "⑨";
        case 138:
            return "⑩";
        case 139:
            return "⓿";
        case 140:
            return "❶";
        case 141:
            return "❷";
        case 142:
            return "❸";
        case 143:
            return "❹";
        case 144:
            return "❺";
        case 145:
            return "❻";
        case 146:
            return "❼";
        case 147:
            return "❽";
        case 148:
            return "❾";
        case 149:
            return "❿";
        case 158:
            return "·";
        case 159:
            return "•";
        case 160:
        case 166:
            return "▪";
        case 161:
            return "○";
        case 162:
        case 164:
            return "⭕";
        case 165:
            return "◎";
        case 167:
            return "✖";
        case 168:
            return "◻";
        case 170:
            return "✦";
        case 171:
            return "★";
        case 172:
            return "✶";
        case 173:
            return "✴";
        case 174:
            return "✹";
        case 175:
            return "✵";
        case 177:
            return "⌖";
        case 178:
            return "⟡";
        case 179:
            return "⌑";
        case 181:
            return "✪";
        case 182:
            return "✰";
        case 195:
        case 197:
        case 215:
        case 219:
        case 223:
        case 231:
            return "◀";
        case 196:
        case 198:
        case 224:
            return "▶";
        case 213:
            return "⌫";
        case 214:
            return "⌦";
        case 216:
            return "➢";
        case 220:
            return "➲";
        case 232:
            return "➔";
        case 233:
        case 199:
        case 200:
        case 217:
        case 221:
        case 225:
            return "◭";
        case 234:
        case 201:
        case 202:
        case 218:
        case 222:
        case 226:
            return "⧨";
        case 239:
            return "⇦";
        case 240:
            return "⇨";
        case 241:
            return "◭";
        case 242:
            return "⧨";
        case 243:
            return "⬄";
        case 244:
            return "⇳";
        case 245:
        case 227:
        case 235:
            return "↖";
        case 246:
        case 228:
        case 236:
            return "↗";
        case 247:
        case 229:
        case 237:
            return "↙";
        case 248:
        case 230:
        case 238:
            return "↘";
        case 249:
            return "▭";
        case 250:
            return "▫";
        case 251:
            return "✗";
        case 252:
            return "✓";
        case 253:
            return "☒";
        case 254:
            return "☑";
        default:
            return xArrow;
    }
}